train:
  data: yolov5/data/custom_dataset.yaml
  weights: yolov5s.pt
  cfg: yolov5/models/yolov5s.yaml
  hyp: yolov5/data/hyps/hyp.scratch-low.yaml
  imgsz: 640
  epochs: 1
  batch-size: 16
  device: 0

val:
  data: yolov5/data/custom_dataset.yaml
  weights: yolov5/runs/train/exp/weights/best.pt
  batch-size: 16
  conf-thres: 0.1
  iou-thres: 0.4
  task: val

detect:
  weights: yolov5/runs/train/exp/weights/best.pt
  source: processed/images/val
  imgsz: 640
  conf-thres: 0.3
  iou-thres: 0.45
  classes: [0, 1]
  hide-labels: True
  hide-conf: True
  save-txt: True
